### PR TITLE
New pay now button

### PR DESCRIPTION
**Pull request by xboxfly15**
I have created a much better button to be used, a much better and more accurate Stripe check out button.

The SVG file is attached below in case you ever want to modify, also shows you what the button looks like.

button-no_alipay

### CODE REVIEW

**Comment by NeverBehave** [comment]
Hi @xboxfly15, thanks for the PR. ~~May I ask where this SVG comes from? Did you make this one yourself?~~
I think from the body of the PR assumes you made this -- Thanks! I would add Alipay to the SVG if you don't mind.

**Comment by xboxfly15** [comment]
Hi, yes I made this myself. It is inspired by the "Pay Now" button on https://github.com/stripe-archive/stripe-payments-demo

No problem, I'll upload a button with Alipay and without and then people can easily choose which one they want.

**Comment by xboxfly15** [comment]
Done!
Here's the SVG with Alipay. I've changed the button.png to be the one with alipay, people can rename the file if they want to use the version without alipay.

button

**Comment by NeverBehave** [comment]
ah you are faster than me, figuring out the right way to edit svg. I will attach my version here as well:

complete1

Let me embed the svg file to the plugin as well, instead of the github issue. Also I would like to credit this in the README if you don't mind. I will update over your branch here.

**Comment by NeverBehave** [comment]
@xboxfly15 Again, thanks for taking time!

**Pull request merged**
