### PR TITLE
Adds currency conversion - fixes a few bugs I was having

### PR DESCRIPTION
**Pull request by xboxfly15**
- Was having an issue with Stripe's currency conversion and clients paying in a currency that Blesta isn't setup for so this fixes it so that the non-exchanged payment amount/currency is used for Blesta (that the amount/currency that the invoice was generated in). If I didn't make this change Blesta credits the client with the exchanged currency amount in the exchanged currency and doesn't apply it to invoices.
- Default to using the email provided by Stripe (and fallback to the id), so the Blesta client profile transactions table extend off the screen with the long reference ids and that hides the date and edit button in Blesta.
- I've also updated the stripe-php dependency to the latest version, I have checked and no breaking code was used between the versions so no code needed to be changed to support the latest version, it is just very good to use the latest version where possible.

I have been using these changes for a week without issue so thought I'd contribute back the changes and share them with everyone.

### CODE REVIEW

**Comment by NeverBehave** [comment]
I am not entirely sure about the ref id overflow, by any chance you have a screenshot of that?
Email is not an unique id to ref an transaction so I am kinda hesitate to do that.

**Comment by xboxfly15** [comment]
Here's a screenshot of the overflow. (not using real numbers, dont worry)
You can also see how the Blesta PayPal gateway does it too, I was using them previously - they use email address.
bc65131714566266ocKbFu961b 1
What it looks like with my change
a8cae61714566351JjJERi962b 1


I understand email not being as unique but the transaction ID is already provided (That's what the "pi_" number is), which is what Stripe use to identify payments, you can see that by going to your Payments view in the Stripe dashboard.

---
At least, I don't think the checkout session ID should be used, Stripe doesn't normally provide that(You have to dig around in the events and logs section to find it), they're very long, and Stripe doesn't provide a filter for it which makes them hard to use.

**Comment by xboxfly15** [comment]
I had a better idea:
Use the customer ID that Stripe provides for someone(they're a number that starts with gcus_ or cus_), they're short enough so they don't overflow and it's unique, plus Stripe provides a filter for customer ID in "More filters" where you can enter the ID to see all payments from that person.

b6c9b41714567276TUZl4a963b 1
---
**EDIT: Looking at this though, it seems the customer ID is rarely populated** https://docs.stripe.com/api/checkout/sessions/object#checkout_session_object-customer only if the customer_creation is set to always.. but customer_email is populated so I'm not sure why. If thats due to the webhook being used?
This is why I used the customer_email in the first place because its populated else we the customer ID can be used instead.

**Comment by NeverBehave** [comment]
Actually lets separate this into a different PR for now --- The currency fix and the SDK update seems to be fine.

For SDK update I believe the `vendor` folder also needs to be updated.

**Pull request closed without merging**
